drop table if exists books;
drop table if exists autors;
drop table if exists genres;

create table autors (
  id int generated by default as identity primary key,
  autor varchar(255) not null
);

create table genres (
  id int generated by default as identity primary key,
  genre varchar(255) not null
);

create table books (
  id int generated by default as identity primary key,
  book varchar(255) not null,
  id_autor integer,
  id_genre integer,
  foreign key (id_autor) references autors (id),
  foreign key (id_genre) references genres (id)
);