drop table if exists comment;
drop table if exists book;
drop table if exists author;
drop table if exists genre;

create table author (
  id bigint generated by default as identity primary key,
  name varchar(255) not null
);

create table genre (
  id bigint generated by default as identity primary key,
  name varchar(255) not null
);

create table book (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  id_author bigint,
  id_genre bigint,
  foreign key (id_author) references author (id),
  foreign key (id_genre) references genre (id)
);

create table comment (
    id bigint generated by default as identity primary key,
    text varchar(255),
    id_book bigint,
    foreign key (id_book) references book (id)
);