drop table if exists books;
drop table if exists authors;
drop table if exists genres;

create table authors (
  id int generated by default as identity primary key,
  author varchar(255) not null
);

create table genres (
  id int generated by default as identity primary key,
  genre varchar(255) not null
);

create table books (
  id int generated by default as identity primary key,
  book varchar(255) not null,
  id_author integer,
  id_genre integer,
  foreign key (id_author) references authors (id),
  foreign key (id_genre) references genres (id)
);